sudo: required

services:
  - docker

language: go
go:
- 1.6
- 1.7
- tip

after_success:
  - |-
    echo $TRAVIS_TAG
    echo $TRAVIS_GO_VERSION
    if [ "$TRAVIS_TAG" != "" ] && [ "$TRAVIS_GO_VERSION" == "1.7" ]
    then
      CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o tcp-paste-linux-amd64
      CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w" -o tcp-paste-darwin-amd64
      CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -ldflags="-s -w" -o tcp-paste-windows-amd64

      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      docker build . -t gregorym/tcp-paste:latest -t gregorym/tcp-paste:$TRAVIS_TAG
      docker push gregorym/tcp-paste
    fi
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: JJqcyV+sh/13xutDJR4Q0IBD5Vx/t5TJ6rq0WBt4ruQCLyrToBpHyh1HVjlYBzNyKdXAJPENZE7FgFJWJ/zRYTn9/QnkIH6Jn7PlaLDc+7apJDffWh9FJNUaDolN4YBZ84rRjM9D/h0iWFO7B/n2o6r/wOPXglxIx3gbue/DIkxgWWBBSR7trYUsbDXYUipHvtbBlKZZZZ+WlAt9JNfgUtBtlvERZsEyw/WTAJnkvSr3CmUZEoZAijNyAIxknbh2Yt9tXAUnu/gkqso3ic68iV7DhwoVsVPJnwVdi5IuZBV/BG7bp/cBcg8ZXRfOKhJREdG+8+p9jj21858yPz1Mr20R7J482J1d15mfYLjRBKG/MKQjoHI6ENOfpASmp1hiwOYiZt2+qhwFMl+K6xbrQ16x7FxM3BQ/9XYSdVnhw8afeF8FoPu+XKt1WY+fluNKxYxiQP8vNHZMxgg9gCyMJ7AM8Pqx2gGd73A2ewgDjWtLkcyDKwz4bLXRrv3/sE6gpiSQKFAEubngdH5Y8/z/GLy0q0es8FHg8mFsulCsHOXm6y/aNrKQDIPcJbRfeSNeInKJNRH1l5lU5wAc+gY0cblUtN7Cx1btSLUcTi4gKqIh3ZKYmZ6XNtlWW+aiJ1aAqOQwOPwjEj2j2rtUbg2IBryCRajadquuItGUCrPqKKA=
  file:
    - tcp-paste-linux-amd64
    - tcp-paste-darwin-amd64
    - tcp-paste-windows-amd64
  on:
    repo: gregory-m/tcp-paste
    condition: $TRAVIS_GO_VERSION = 1.7
    tags: true
