sudo: required

services:
  - docker

language: go
go:
- 1.6
- 1.7
- tip

after_success:
  - |-
    echo $TRAVIS_TAG
    echo $TRAVIS_GO_VERSION
    if [ "$TRAVIS_TAG" != "" ] && [ "$TRAVIS_GO_VERSION" == "1.7" ]
    then
      CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o tcp-paste-linux-amd64
      CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w" -o tcp-paste-darwin-amd64
      CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -ldflags="-s -w" -o tcp-paste-windows-amd64

      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      docker build . -t gregorym/tcp-paste:latest -t gregorym/tcp-paste:$TRAVIS_TAG
      docker push gregorym/tcp-paste
    fi
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: Da0ADHnxJWVRsGsc00fh9EeNgN7WrRaog/Q6oRJNnQaITMlVQG3J8ZUJ7XKRS1zYrPRQPQYtKFUXMRGTrbiAZD92xrB1oAixoz+FIkYZd447meX19CnBE4i2NE0uVkK0v3S+yDSKToSav3p8BT3UGWCfxlwWI5ZCvezWKycYPqpnhFLIVNzjTDPrjDC0iPJFfdxeZQM/eea9tVFaXLj08G3UdO10jFuh+iSDRtIhYlAyQglmLtfNxkivw+X5wRJlG9MdPC15sgz1TxjpMjuYia/Wod9HdSMuI/iaWOwmcRWMM+Zf9DB6CwwvoV8tJEgQT/Iheo6rpVw4GRCqLtmMC5il9Kprqg5e8DxFSZdhC9+gF/GtLdMSCyZNShXwtmP2Tuk+hgDg9ORw7Kfn43R99oRWrobTCGZQhd95d5t5ms2+TOxIm9BMH/KhAfNBK9oUMaCXGi5jYPgiqHlcTZkDhVsA4Qlp/t8XZUNDvOHOOEmBxyjQOWDHTmneQTqqJ8mEt9RPC8kqTWsgWmMcb8b4fWH690wugJGZTeXEf7O/nW5yLa+2gcHwYuJiXWWxljlJQW3pzcOnIjXfmR3ZJ5oEKW04gWlW7XzxCbY9v18mg8IESoJNAlYjCXpXjPTtePOGSOl3a2jBj8dePd7EFYwozDSa/3kNY74IPvWKZ3C6iHc=
  file:
    - tcp-paste-linux-amd64
    - tcp-paste-darwin-amd64
    - tcp-paste-windows-amd64
  on:
    repo: gregory-m/tcp-paste
    condition: $TRAVIS_GO_VERSION = 1.7
    tags: true
